<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EzPoco" Version="0.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="ServiceStack.OrmLite.Core" Version="6.9.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.10" />
  </ItemGroup>

</Project>
